"""Machine-readable inventory of PostgreSQL writers currently measured."""

from __future__ import annotations


WRITERS: tuple[dict[str, object], ...] = (
    {"writer_id": "schema.migration", "metric_kind": "central_schema",
     "source": "central server startup schema migration", "storage": "postgres",
     "tables": ["central_schema_migrations", "migration-defined central schema"],
     "durability": "schema_version_and_compatible_central_schema",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "one native connection-context transaction per initialize call; records full migration plan and no-op startup checks"},
    {"writer_id": "rest.query_cache", "metric_kind": "query_cache",
     "source": "Kiwoom REST responses with persistent cache TTL", "storage": "postgres",
     "tables": ["central_api_query_cache"], "durability": "rebuildable_cache",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "legacy success timing plus common DB success/error/close/commit timing"},
    {"writer_id": "rest.market_bars.minute", "metric_kind": "query_minute",
     "source": "ka10080", "storage": "postgres",
     "tables": ["central_minute_bars", "central_market_data_observation_meta",
                "central_observation_revisions"], "durability": "market_data_and_provenance",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "connect/bars/metadata/revisions/commit/total plus correlated common DB call"},
    {"writer_id": "rest.market_bars.daily", "metric_kind": "query_daily",
     "source": "ka10081", "storage": "postgres",
     "tables": ["central_daily_bars", "central_market_data_observation_meta"],
     "durability": "market_data_and_provenance", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "connect/bars/metadata/revisions/commit/total plus correlated common DB call"},
    {"writer_id": "realtime.latest", "metric_kind": "realtime_latest",
     "source": "Kiwoom WebSocket realtime event types", "storage": "postgres",
     "tables": ["central_realtime_latest"], "durability": "latest_projection",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "legacy success total correlated with one native transaction"},
    {"writer_id": "realtime.minute", "metric_kind": "realtime_minute",
     "source": "0B aggregation/flush", "storage": "postgres",
     "tables": ["central_minute_bars", "central_market_data_observation_meta",
                "central_observation_revisions", "central_minute_bar_operations"],
     "durability": "realtime_bars_and_idempotency", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "legacy success total correlated with one native transaction; rows are input deltas"},
    {"writer_id": "realtime.minute_finalize", "metric_kind": "realtime_minute_finalize",
     "source": "0B minute finalization", "storage": "postgres",
     "tables": ["central_minute_bars", "central_observation_revisions",
                "central_minute_bar_operations"], "durability": "finalized_bar_and_idempotency",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "legacy success total correlated with one native transaction; rows are closures"},
    {"writer_id": "realtime.second_bar", "metric_kind": "realtime_second_bar",
     "source": "0B second aggregation/flush", "storage": "postgres",
     "tables": ["central_second_trade_bars"], "durability": "realtime_bars",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "legacy success total correlated with one native transaction; rows are absolute bars"},
    {"writer_id": "dataset.snapshot", "metric_kind": "dataset:*",
     "source": "REST response handler and central collectors", "storage": "postgres",
     "tables": ["central_dataset_snapshots", "central_market_data_observation_meta",
                "central_observation_revisions"], "durability": "latest_and_observation_history",
     "diagnostic_pause_supported": False, "measurement": "successful transaction total; kind is dynamic",
    "common_db_observed_kinds": ["dataset:market_state", "dataset:new_high",
                                  "dataset:program_flow", "dataset:ranking",
                                  "dataset:top20_membership", "dataset:top20_index",
                                  "dataset:market_index_chart", "dataset:investor_flow",
                                  "dataset:stock_fundamentals", "dataset:nxt_eligibility"]},
    {"writer_id": "dataset.statistics_cache", "metric_kind": "dataset:top20_statistics_day",
     "source": "TOP20 statistics reader cache fill", "storage": "postgres",
     "tables": ["central_dataset_snapshots"], "durability": "derived_daily_cache",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "warm read and cold cache fill share the native connection transaction"},
    {"writer_id": "research.observation_export", "metric_kind": "research_observation_export_create",
     "source": "research observations API without an existing watermark", "storage": "postgres",
     "tables": ["central_research_exports", "central_research_export_members"],
     "durability": "fixed_manifest_and_ordered_revision_membership",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "one native transaction for revision selection, manifest and members; rows attempted unknown until selection"},
    {"writer_id": "document.collection", "metric_kind": "document:*",
     "source": "REST response handler and central services", "storage": "postgres",
     "tables": ["central_documents", "central_theme_snapshots",
                "central_news_article_revisions", "central_news_jobs"],
     "durability": "latest_projection_and_selected_history",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["document:news_article", "document:news_ai",
                                  "document:news_ai_shared", "document:news_request_usage",
                                  "document:journal_news_link",
                                  "document:journal_v2_news_links",
                                  "document:journal_settings", "document:journal_fills",
                                  "document:journal_reviews", "document:journal_setups",
                                  "document:journal_cycle_overrides",
                                  "document:journal_group_overrides",
                                  "document:journal_entry_snapshots",
                                  "document:journal_costs", "document:journal_stocks",
                                  "document:journal_backfill",
                                  "document:journal_v2_fills", "document:journal_v2_reviews",
                                  "document:journal_v2_setups",
                                  "document:journal_v2_cycle_overrides",
                                  "document:journal_v2_group_overrides",
                                  "document:journal_v2_entry_snapshots",
                                  "document:journal_v2_costs",
                                  "document:journal_v2_enrichment_tasks",
                                  "document:journal_v2_analysis_revisions",
                                  "document:journal_v2_research_links",
                                  "document:journal_sync_states",
                                  "document:journal_v2_sync_states",
                                  "document:app_settings",
                                  "document:app_column_settings",
                                  "document:news_sync",
                                  "document:news_watchlist",
                                  "document:news_automation_settings",
                                  "document:server_operational_settings",
                                  "document:theme_profile", "document:theme_stock",
                                  "document:theme_metadata",
                                  "document:krx_trading_day_observations",
                                  "document:external_market_roll_state",
                                  "document:stock_catalog",
                                  "document:minute_trade_value_comparisons",
                                  "document:stock_nxt_eligibility",
                                  "document:stock_fundamentals",
                                  "document:account_entry_symbols_daily",
                                  "document:stock_price_references",
                                  "document:top20_daily_entrants",
                                  "document:historical_highs",
                                  "document:market_index_chart_coverage",
                                  "document:market_data_coverage_daily",
                                  "document:market_data_coverage",
                                  "document:market_data_coverage_intraday",
                                  "document:candidate_flow_capture",
                                  "document:candidate_flow_finalization",
                                  "document:condition_search_status",
                                  "document:market_event_sessions",
                                  "document:news_original_publication",
                                  "document:external_market_collection_status",
                                  "document:news_assessment",
                                  "document:execution_forward_profiles",
                                  "document:execution_forward_reports",
                                  "document:execution_strategy_stage_revisions",
                                  "document:execution_feedback_evidence",
                                  "document:execution_feedback_reviews",
                                  "document:execution_feedback_improvement_proposals",
                                  "document:execution_feedback_strategy_versions",
                                  "document:execution_feedback_revalidation_requests",
                                  "document:execution_feedback_revalidation_receipts",
                                  "document:execution_mock_automation_specs",
                                  "document:execution_mock_automation_admissions",
                                  "document:execution_mock_automation_admission_by_spec",
                                  "document:execution_mock_automation_lease_receipts",
                                  "document:execution_mock_automation_lease_by_admission",
                                  "document:execution_mock_automation_candidate_packages",
                                  "document:execution_mock_automation_eligibility_policies",
                                  "document:execution_mock_automation_eligibility_receipts",
                                  "document:execution_mock_automation_runner_current",
                                  "document:credential_vault_state",
                                  "document:execution_mock_automation_risk_snapshots",
                                  "document:execution_mock_automation_current_risk",
                                  "document:execution_mock_automation_recovery_decisions",
                                  "document:execution_mock_automation_current_recovery",
                                  "document:execution_mock_automation_decision_gates",
                                  "document:execution_mock_automation_approved_gates",
                                  "document:execution_mock_automation_dispatch_receipts",
                                  "document:execution_mock_automation_dispatch_by_intent",
                                  "document:execution_mock_automation_stop_revisions",
                                  "document:execution_mock_automation_current_stop"],
     "measurement": "successful transaction total; common DB timing for explicitly listed kinds only"},
    {"writer_id": "mock_automation.control", "metric_kind": "mock_automation_control",
     "source": "mock automation admission, emergency stop, and resume", "storage": "postgres",
     "tables": ["central_documents"], "durability": "account_control_state",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "one native transaction per call; revision conflicts return false and still commit"},
    {"writer_id": "market_event.revision", "metric_kind": "market_event:*",
     "source": "MarketEventService VI, hot cohort, and upper-limit facts", "storage": "postgres",
     "tables": ["central_vi_event_revisions", "central_hot_cohort_revisions",
                "central_hot_cohort_current", "central_upper_limit_fact_revisions"],
     "durability": "immutable_event_history_and_current_cohort_projection",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["market_event:vi", "market_event:hot_cohort",
                                  "market_event:upper_limit"],
     "measurement": "one native transaction per method call; cohort rows_attempted includes optional current projection"},
    {"writer_id": "news.job_claim", "metric_kind": "news_job_claim",
     "source": "news worker claim", "storage": "postgres",
     "tables": ["central_news_jobs"], "durability": "job_ownership", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "legacy success timing plus common DB success/error/close/commit timing"},
    {"writer_id": "news.job_enqueue", "metric_kind": "news_ai_job_enqueue",
     "source": "NewsService AI job scheduling", "storage": "postgres",
     "tables": ["central_news_article_revisions", "central_news_body_revisions",
                "central_news_jobs"], "durability": "job_queue_and_revision_reference",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "common DB timing; rows_attempted counts candidates, not inserted jobs"},
    {"writer_id": "news.source_page", "metric_kind": "news_source:*",
     "source": "query-set and Naver Stock market news collectors", "storage": "postgres",
     "tables": ["central_news_article_revisions", "central_news_article_target_revisions",
                "central_news_jobs", "central_news_source_observations",
                "central_news_source_runs", "central_news_source_cursors"],
     "durability": "article_history_and_source_progress",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["news_source:query_set", "news_source:naver_stock_market"],
     "measurement": "common DB timing; rows_attempted counts page items, not run or cursor writes"},
    {"writer_id": "news.request_budget", "metric_kind": "news_request:*",
     "source": "query-set and watchlist Naver news request claims", "storage": "postgres",
     "tables": ["central_news_request_budget"], "durability": "daily_request_budget",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["news_request:query_set", "news_request:watchlist"],
     "measurement": "common DB timing; each claim commits even when the limit rejects it"},
    {"writer_id": "news.historical_market_batch", "metric_kind": "news_historical_market:*",
     "source": "prepared historical Naver Stock market news importer", "storage": "postgres",
     "tables": ["central_news_article_revisions", "central_news_article_target_revisions",
                "central_news_jobs", "central_news_source_observations",
                "central_news_source_runs", "central_news_source_cursors"],
     "durability": "historical_market_article_and_progress", "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["news_historical_market:flash", "news_historical_market:world"],
     "measurement": "common DB timing; advisory-lock replay commits without rewriting the batch"},
    {"writer_id": "maintenance.prepared_news", "metric_kind": "prepared_news_completion_batch",
     "source": "prepared historical news importer BODY/RULE completion batch",
     "storage": "postgres",
     "tables": ["central_news_jobs", "central_news_body_revisions",
                "central_documents"],
     "durability": "completed_body_rule_and_job_state",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "one caller-owned outer transaction per batch; article savepoints remain native and are not separate DB calls"},
    {"writer_id": "news.job_finish", "metric_kind": "news_job_finish",
     "source": "news worker completion", "storage": "postgres",
     "tables": ["central_news_jobs"], "durability": "job_state", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "legacy success timing plus common DB success/error/close/commit timing"},
    {"writer_id": "news.job_retry", "metric_kind": "news_job_retry",
     "source": "news worker retry", "storage": "postgres",
     "tables": ["central_news_jobs"], "durability": "job_state", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "common DB success/error/close/commit timing"},
    {"writer_id": "news.external_claim", "metric_kind": "news_external_claim",
     "source": "historical news PC claim", "storage": "postgres",
     "tables": ["central_news_jobs", "central_news_article_revisions"],
     "durability": "job_ownership", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "existing slow-claim wait log plus common DB success/error/close/commit timing"},
    {"writer_id": "news.external_finish", "metric_kind": "news_external_finish:*",
     "source": "historical news PC BODY/RULE completion", "storage": "postgres",
     "tables": ["central_news_jobs", "central_news_body_revisions",
                "central_news_article_revisions", "central_news_event_revisions",
                "central_news_event_membership_revisions", "central_documents"],
     "durability": "body_or_rule_result_and_job_state", "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["news_external_finish:BODY", "news_external_finish:RULE"],
     "measurement": "one native transaction per completion; one job attempted including replay or error"},
    {"writer_id": "news.body", "metric_kind": "news_body",
     "source": "news BODY worker", "storage": "postgres",
     "tables": ["central_news_body_revisions", "central_news_article_revisions",
                "central_news_jobs"], "durability": "article_body_history",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "legacy success timing plus common DB success/error/close/commit timing"},
    {"writer_id": "news.ai_results", "metric_kind": "news_ai_results",
     "source": "CentralAIService analysis", "storage": "postgres",
     "tables": ["central_documents", "central_news_ai_revisions"],
     "durability": "latest_projection_immutable_revision_and_request_usage",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "common DB success/error/close/commit timing"},
    {"writer_id": "news.event", "metric_kind": "news_event",
     "source": "news RULE worker via save_news_event_revision", "storage": "postgres",
     "tables": ["central_news_event_revisions", "central_news_event_membership_revisions",
                "central_news_article_revisions"], "durability": "event_and_membership_history",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "common DB timing for the normal RULE writer; external job completion remains separate"},
    {"writer_id": "external_market.bars", "metric_kind": "external_market_bars",
     "source": "Yahoo delayed market collector", "storage": "postgres",
     "tables": ["central_external_bars"], "durability": "delayed_market_bars",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "common DB timing; 5m and 1d fetches retain separate native transactions"},
    {"writer_id": "candidate.shadow_evaluation", "metric_kind": "shadow_evaluation",
     "source": "CandidateMonitor per observation evaluation", "storage": "postgres",
     "tables": ["central_shadow_decisions", "central_shadow_candidate_events"],
     "durability": "immutable_shadow_decision_and_optional_candidate_event",
     "diagnostic_pause_supported": True, "common_db_observed": True,
     "measurement": "one native transaction per evaluation; rows count decision and optional event"},
    {"writer_id": "candidate.shadow_checkpoint", "metric_kind": "shadow_monitor_state",
     "source": "CandidateMonitor bootstrap and poll checkpoint", "storage": "postgres",
     "tables": ["central_shadow_monitor_state"], "durability": "replay_checkpoint",
     "diagnostic_pause_supported": True, "common_db_observed": True,
     "measurement": "one separate native transaction per checkpoint after the poll batch"},
    {"writer_id": "execution.intent", "metric_kind": "execution_intent",
     "source": "ExecutionRepository intent creation", "storage": "postgres",
     "tables": ["central_execution_intents", "central_execution_runtime_leases"],
     "durability": "order_intent", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "one native transaction; ownership lease check and idempotent insert"},
    {"writer_id": "execution.event", "metric_kind": "execution_event",
     "source": "ExecutionRepository event application", "storage": "postgres",
     "tables": ["central_execution_events", "central_execution_intents",
                "central_execution_runtime_leases"],
     "durability": "event_history_and_intent_projection", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "one native transaction for event insert and intent update; one logical event attempted"},
    {"writer_id": "execution.account_snapshot", "metric_kind": "execution_account_snapshot",
     "source": "ExecutionRepository account snapshot", "storage": "postgres",
     "tables": ["central_execution_account_snapshots", "central_execution_runtime_leases"],
     "durability": "account_execution_snapshot", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "one native transaction; ownership lease check and idempotent insert"},
    {"writer_id": "execution.runtime_lease", "metric_kind": "execution_runtime:*",
     "source": "ExecutionRepository runtime ownership", "storage": "postgres",
     "tables": ["central_execution_runtime_leases"], "durability": "mock_runtime_ownership",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["execution_runtime_acquire", "execution_runtime_release"],
     "measurement": "independent native transaction per acquire or release; rejected CAS still commits"},
    {"writer_id": "account.identity", "metric_kind": "account_identity_register",
     "source": "verified Kiwoom account identity registration", "storage": "postgres",
     "tables": ["central_account_registry"], "durability": "verified_account_identity",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "one native transaction per registration; replay returns the existing account ref"},
    {"writer_id": "account.binding", "metric_kind": "account_binding_append",
     "source": "legacy and bootstrap verified account binding", "storage": "postgres",
     "tables": ["central_account_registry", "central_account_binding_revisions"],
     "durability": "binding_revision_history", "diagnostic_pause_supported": False,
     "common_db_observed": True,
     "measurement": "one native transaction; advisory lock protects per-profile revision; credential activation finalize remains a separate writer"},
    {"writer_id": "credential.activation", "metric_kind": "credential_activation_finalize",
     "source": "CredentialRuntime apply/recovery and legacy vault import", "storage": "postgres",
     "tables": ["central_account_registry", "central_account_binding_revisions",
                "central_credential_profiles", "central_credential_activations",
                "central_documents"],
     "durability": "activation_receipt_binding_and_account_settings",
     "diagnostic_pause_supported": False, "common_db_observed": True,
     "measurement": "one native transaction after vault file commit; global advisory lock, replay and rollback observed without credential values"},
    {"writer_id": "credential.profile", "metric_kind": "credential_profile:*",
     "source": "CredentialRuntime profile API and startup owner registration", "storage": "postgres",
     "tables": ["central_credential_profiles", "central_documents"],
     "durability": "credential_profile_lifecycle_and_create_request_receipt",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["credential_profile_create", "credential_profile_archive",
                                  "credential_profile_rename", "credential_profile_register"],
     "measurement": "four independent native transactions using the existing global credential-activation advisory lock; create receipt and draft profile share one transaction"},
    {"writer_id": "account.real_monitor", "metric_kind": "real_account:*",
     "source": "RealAccountRuntime event queue and periodic REST recovery", "storage": "postgres",
     "tables": ["central_documents"], "durability": "real_account_evidence",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["real_account_event", "real_account_recovery"],
     "measurement": "one native transaction per event or recovery snapshot; existing credential-activation advisory lock and independent async-to-thread calls retained"},
    {"writer_id": "account.settings", "metric_kind": "account_settings:*",
     "source": "RealAccountRuntime, MockAccountRuntime and real market-role change",
     "storage": "postgres", "tables": ["central_documents"],
     "durability": "account_and_market_profile_settings_cas",
     "diagnostic_pause_supported": False,
     "common_db_observed_kinds": ["account_settings_save", "market_profile_settings_save"],
     "measurement": "separate native CAS transactions; existing credential-activation advisory lock and runtime drain/fence retained"},
)


def writer_registry() -> list[dict[str, object]]:
    return [dict(value) for value in WRITERS]
